config/routes.rb
Bulls::Application.routes.draw do
  resources :articles

  resources :chat_messages

  resources :achievements

  resources :authentications
  
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users
  
  resources :users

  resources :games
  
  resources :home
  
  resources :pusher

  root :to => "home#index"
  
  match '/chat', :to => 'home#chat'
  match '/error', :to => 'home#error'
  match '/denied', :to => 'home#denied'
  match '/pusher/auth', :to => 'pusher#auth'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, :dependent => :destroy
  has_many :chat_messages, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :display_name
  
  #custom validation for sign in forms that only have an email address
  validates :display_name, :uniqueness => true, :display_name => true, :allow_nil => true
  # validates :email, :uniqueness => true, :email => true
  
  after_create :set_temp_display_name
  
  def apply_omniauth(omniauth)
    set_email(omniauth['user_info']['email'])
    set_display_name(omniauth['user_info']['nickname'])
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid']) 
  end

  def password_required?
    authentications.empty? && email.nil?
  end
  
  def set_display_name(disp_name)
    #for omniauth accounts
    if User.all.map {|u| u.display_name}.include?(disp_name)
      self.display_name = disp_name + rand(100000).to_s
    else 
      self.display_name = disp_name
    end
  end
  
  def set_temp_display_name
    #for regular accounts
    if !display_name
      display_name = "Bulls Fan " + id.to_s
    end
  end
  
  def set_email(email)
    # if email.nil?
    #   self.email = " "
    # else
    #   self.email = email if email.blank?
    # end
  end
  

  
end

app/controllers/users_controller.rb
# Overrides defaults used by Devise to allow administrators
# to create and edit accounts. Users can edit their own accounts.

class UsersController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource :user

  # get :index
  # List all user accounts
  def index
    @users = User.all
  end
  
  # get :show
  # Show an individual user
  def show
  end

  # get :new
  # Display a form to create a new user
  def new
    @user = User.new
  end

  # post :create
  # Process data to create a new user
  def create            
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created user."
      redirect_to users_url
    else
      render :action => 'new'
    end
  end

  # get :edit
  # Display a form to edit a user
  def edit
  end

  # put :update
  # Process data to update a user
  def update    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated information."
      redirect_to edit_user_path(@user)
    else
      render :action => 'edit'
    end
  end

  # delete :destroy
  # Delete a user account
  def destroy
    @user.destroy
    flash[:notice] = "Successfully destroyed user."
    redirect_to users_url
  end
end

app/views/users/_form.html.haml
= error_messages_for @user
= simple_form_for user do |f|

  = f.input :display_name
  = f.input :email, :required => current_user.password_required?, :label => "Email (will not be visible to anyone)"
  - if @user.password_required?
    = f.input :password
    = f.input :password_confirmation, :label => 'Confirm Password'
    
  = f.button :submit, :value => 'Submit', :class => 'button large'

app/views/users/edit.html.haml
- title "Account Info"

#general_form
  = render 'form', :user => @user
  
%p
  = link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete

app/views/users/index.html.haml
- title "Users"

%table
  %tr
    %th Name
    %th Email
    %th Last Login
  - for user in @users
    %tr{ :class => cycle("odd", "even") }
      %td=link_to user.fullname, user
      %td= user.email
      %td= nice_date(user.last_sign_in_at) unless user.last_sign_in_at.nil?

%p= link_to "New User", new_user_path, :class => 'button'

app/views/users/new.html.haml
- title "New User"

= render 'form', :user => @user

%p= link_to "Back to List", users_path, :class => 'button'

app/views/users/show.html.haml
- title @user.fullname

%p
  = @user.school.name

%p
  %strong Email:
  = @user.email
%p
  %strong Roles:
  - @user.roles.each do |role|
    = role.name

%p
  - if can? (:edit, @user)
    = link_to "Edit", edit_user_path(@user), :class => 'button'
  - if can? (:destroy, @user)
    = link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete, :class => 'button'
    = link_to "View All", users_path, :class => 'button'

%h2 Video Clips

%ul
- @user.video_clips.each do |clip|
  %li= link_to nice_date(clip.taken_on), clip