config/routes.rb
Bulls::Application.routes.draw do
  resources :articles

  resources :chat_messages

  resources :achievements

  resources :authentications
  
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users
  
  resources :users

  resources :games
  
  resources :home
  
  resources :pusher

  root :to => "home#index"
  
  match '/chat', :to => 'home#chat'
  match '/error', :to => 'home#error'
  match '/denied', :to => 'home#denied'
  match '/pusher/auth', :to => 'pusher#auth'
  
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  attr_accessible :user_id, :message
  
  belongs_to :user
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  def index
    @chat_messages = ChatMessage.all
  end

  def show
    @chat_message = ChatMessage.find(params[:id])
  end

  def new
    @chat_message = ChatMessage.new
  end

  def create
    # @chat_message = ChatMessage.create!(params[:chat_message])
    # @chat_message = params[:chat_message][:message].to_s
    # @chat_username = current_user.display_name
    # @chat_created_at = Time.now.strftime("%l:%M")
    #my Pusher Config
    if !params[:chat_message][:message].blank?
      Pusher['presence-bulls_zone'].trigger('send_chat', {
        :message => params[:chat_message][:message].to_s, 
        :created_at => Time.now.strftime("%l:%M"),
        :username => (current_user.nil? ? "Guest" : current_user.display_name.to_s)
      })
    end
  end

  def edit
    @chat_message = ChatMessage.find(params[:id])
  end

  def update
    @chat_message = ChatMessage.find(params[:id])
    if @chat_message.update_attributes(params[:chat_message])
      redirect_to @chat_message, :notice  => "Successfully updated chat message."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @chat_message = ChatMessage.find(params[:id])
    @chat_message.destroy
    redirect_to chat_messages_url, :notice => "Successfully destroyed chat message."
  end
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/views/chat_messages/_chat_message.html.haml
%li
  %span.created_at
    = message.created_at.strftime("%H:%M")
  = message.content

app/views/chat_messages/_form.html.haml
= form_for @chat_message do |f|
  = f.error_messages
  %p
    = f.label :user_id
    %br
    = f.text_field :user_id
  %p
    = f.label :message
    %br
    = f.text_area :message
  %p
    = f.submit

app/views/chat_messages/create.js.erb
// $("#new_chat_message")[0].reset();
$("#chat_room").attr({ scrollTop: $("#chat_room").attr("scrollHeight") });

app/views/chat_messages/edit.html.haml
- title "Edit Chat Message"

= render 'form'

%p
  = link_to "Show", chat_message
  |
  = link_to "View All", chat_messages_path

app/views/chat_messages/index.html.haml
- title "Chat Messages"

%table
  %tr
    %th User
    %th Message
  - for chat_message in @chat_messages
    %tr
      %td= chat_message.user_id
      %td= chat_message.message
      %td= link_to 'Show', chat_message
      %td= link_to 'Edit', edit_chat_message_path(chat_message)
      %td= link_to 'Destroy', chat_message, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Chat Message", new_chat_message_path

app/views/chat_messages/new.html.haml
- title "New Chat Message"

= render 'form'

%p= link_to "Back to List", chat_messages_path

app/views/chat_messages/show.html.haml
- title "Chat Message"

%p
  %strong User:
  = @chat_message.user_id
%p
  %strong Message:
  = @chat_message.message

%p
  = link_to "Edit", edit_chat_message_path(@chat_message)
  |
  = link_to "Destroy", @chat_message, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", chat_messages_path