config/routes.rb
Bulls::Application.routes.draw do
  resources :articles

  resources :chat_messages

  resources :achievements

  resources :authentications
  
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users
  
  resources :users

  resources :games
  
  resources :home
  
  resources :pusher

  root :to => "home#index"
  
  match '/chat', :to => 'home#chat'
  match '/error', :to => 'home#error'
  match '/denied', :to => 'home#denied'
  match '/pusher/auth', :to => 'pusher#auth'
  
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      =  "Bulls Zone " + yield(:title).to_s
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8", :application_type => 'browser'}/

    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
  #container
    #navbar
      #navbar_content
        #logo
          = link_to image_tag("bulls-logo-black.jpg"), root_path
        #nav
          = link_to("Blog", articles_path)
          = link_to("Forums", "#")
          = link_to("Chat", chat_path)
          = link_to("Schedule", games_path)
          = link_to("Bulls Feed", "#")
    
          #nav_login
            - if user_signed_in?
              %span.menu_display_name= link_to current_user.display_name, edit_user_path(current_user)
              = link_to "Sign Out", destroy_user_session_path
            - else
              = link_to "Sign In/Sign Up!", new_user_session_path, :class => "nav_login_link"

    #main_content
      / #nav_login_form
      /   = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
      /     = f.label :email
      /     = f.text_field :email
      /     
      /     = f.label :password
      /     = f.password_field :password
      /  
      /     - if devise_mapping.rememberable?
      /       = f.check_box :remember_me
      /       = f.label :remember_me
      / 
      /     = f.submit "Sign in"
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)
      = yield
    
  #footer
    Copyright Bulls Zone Inc. 
    = Date.today.year 
    all rights reserved
    %br
    = link_to "Contact", "#" 
    | 
    = link_to "Help", "#" 
    | 
    = link_to "Site Map", "#"